/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedServicesRouteImport } from './routes/_authenticated/services'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedDevisIndexRouteImport } from './routes/_authenticated/devis.index'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/clients.index'
import { Route as AuthenticatedDevisNewRouteImport } from './routes/_authenticated/devis.new'
import { Route as AuthenticatedDevisIdRouteImport } from './routes/_authenticated/devis.$id'
import { Route as AuthenticatedClientsNewRouteImport } from './routes/_authenticated/clients.new'
import { Route as AuthenticatedClientsIdRouteImport } from './routes/_authenticated/clients.$id'
import { Route as AuthenticatedClientsIdEditRouteImport } from './routes/_authenticated/clients.$id.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedServicesRoute = AuthenticatedServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDevisIndexRoute = AuthenticatedDevisIndexRouteImport.update({
  id: '/devis/',
  path: '/devis/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClientsRoute,
  } as any)
const AuthenticatedDevisNewRoute = AuthenticatedDevisNewRouteImport.update({
  id: '/devis/new',
  path: '/devis/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDevisIdRoute = AuthenticatedDevisIdRouteImport.update({
  id: '/devis/$id',
  path: '/devis/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientsNewRoute = AuthenticatedClientsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedClientsRoute,
} as any)
const AuthenticatedClientsIdRoute = AuthenticatedClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedClientsRoute,
} as any)
const AuthenticatedClientsIdEditRoute =
  AuthenticatedClientsIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedClientsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/clients': typeof AuthenticatedClientsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/services': typeof AuthenticatedServicesRoute
  '/clients/$id': typeof AuthenticatedClientsIdRouteWithChildren
  '/clients/new': typeof AuthenticatedClientsNewRoute
  '/devis/$id': typeof AuthenticatedDevisIdRoute
  '/devis/new': typeof AuthenticatedDevisNewRoute
  '/clients/': typeof AuthenticatedClientsIndexRoute
  '/devis/': typeof AuthenticatedDevisIndexRoute
  '/clients/$id/edit': typeof AuthenticatedClientsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/services': typeof AuthenticatedServicesRoute
  '/clients/$id': typeof AuthenticatedClientsIdRouteWithChildren
  '/clients/new': typeof AuthenticatedClientsNewRoute
  '/devis/$id': typeof AuthenticatedDevisIdRoute
  '/devis/new': typeof AuthenticatedDevisNewRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/devis': typeof AuthenticatedDevisIndexRoute
  '/clients/$id/edit': typeof AuthenticatedClientsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/services': typeof AuthenticatedServicesRoute
  '/_authenticated/clients/$id': typeof AuthenticatedClientsIdRouteWithChildren
  '/_authenticated/clients/new': typeof AuthenticatedClientsNewRoute
  '/_authenticated/devis/$id': typeof AuthenticatedDevisIdRoute
  '/_authenticated/devis/new': typeof AuthenticatedDevisNewRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
  '/_authenticated/devis/': typeof AuthenticatedDevisIndexRoute
  '/_authenticated/clients/$id/edit': typeof AuthenticatedClientsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/clients'
    | '/dashboard'
    | '/services'
    | '/clients/$id'
    | '/clients/new'
    | '/devis/$id'
    | '/devis/new'
    | '/clients/'
    | '/devis/'
    | '/clients/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/services'
    | '/clients/$id'
    | '/clients/new'
    | '/devis/$id'
    | '/devis/new'
    | '/clients'
    | '/devis'
    | '/clients/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/clients'
    | '/_authenticated/dashboard'
    | '/_authenticated/services'
    | '/_authenticated/clients/$id'
    | '/_authenticated/clients/new'
    | '/_authenticated/devis/$id'
    | '/_authenticated/devis/new'
    | '/_authenticated/clients/'
    | '/_authenticated/devis/'
    | '/_authenticated/clients/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/services': {
      id: '/_authenticated/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AuthenticatedServicesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/devis/': {
      id: '/_authenticated/devis/'
      path: '/devis'
      fullPath: '/devis/'
      preLoaderRoute: typeof AuthenticatedDevisIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedClientsRoute
    }
    '/_authenticated/devis/new': {
      id: '/_authenticated/devis/new'
      path: '/devis/new'
      fullPath: '/devis/new'
      preLoaderRoute: typeof AuthenticatedDevisNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/devis/$id': {
      id: '/_authenticated/devis/$id'
      path: '/devis/$id'
      fullPath: '/devis/$id'
      preLoaderRoute: typeof AuthenticatedDevisIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients/new': {
      id: '/_authenticated/clients/new'
      path: '/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof AuthenticatedClientsNewRouteImport
      parentRoute: typeof AuthenticatedClientsRoute
    }
    '/_authenticated/clients/$id': {
      id: '/_authenticated/clients/$id'
      path: '/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof AuthenticatedClientsIdRouteImport
      parentRoute: typeof AuthenticatedClientsRoute
    }
    '/_authenticated/clients/$id/edit': {
      id: '/_authenticated/clients/$id/edit'
      path: '/edit'
      fullPath: '/clients/$id/edit'
      preLoaderRoute: typeof AuthenticatedClientsIdEditRouteImport
      parentRoute: typeof AuthenticatedClientsIdRoute
    }
  }
}

interface AuthenticatedClientsIdRouteChildren {
  AuthenticatedClientsIdEditRoute: typeof AuthenticatedClientsIdEditRoute
}

const AuthenticatedClientsIdRouteChildren: AuthenticatedClientsIdRouteChildren =
  {
    AuthenticatedClientsIdEditRoute: AuthenticatedClientsIdEditRoute,
  }

const AuthenticatedClientsIdRouteWithChildren =
  AuthenticatedClientsIdRoute._addFileChildren(
    AuthenticatedClientsIdRouteChildren,
  )

interface AuthenticatedClientsRouteChildren {
  AuthenticatedClientsIdRoute: typeof AuthenticatedClientsIdRouteWithChildren
  AuthenticatedClientsNewRoute: typeof AuthenticatedClientsNewRoute
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
}

const AuthenticatedClientsRouteChildren: AuthenticatedClientsRouteChildren = {
  AuthenticatedClientsIdRoute: AuthenticatedClientsIdRouteWithChildren,
  AuthenticatedClientsNewRoute: AuthenticatedClientsNewRoute,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
}

const AuthenticatedClientsRouteWithChildren =
  AuthenticatedClientsRoute._addFileChildren(AuthenticatedClientsRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedServicesRoute: typeof AuthenticatedServicesRoute
  AuthenticatedDevisIdRoute: typeof AuthenticatedDevisIdRoute
  AuthenticatedDevisNewRoute: typeof AuthenticatedDevisNewRoute
  AuthenticatedDevisIndexRoute: typeof AuthenticatedDevisIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedClientsRoute: AuthenticatedClientsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedServicesRoute: AuthenticatedServicesRoute,
  AuthenticatedDevisIdRoute: AuthenticatedDevisIdRoute,
  AuthenticatedDevisNewRoute: AuthenticatedDevisNewRoute,
  AuthenticatedDevisIndexRoute: AuthenticatedDevisIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
