/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDevisIndexRouteImport } from './routes/_authenticated/devis.index'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/clients.index'
import { Route as AuthenticatedDevisNewRouteImport } from './routes/_authenticated/devis.new'
import { Route as AuthenticatedDevisDevisIdRouteImport } from './routes/_authenticated/devis.$devisId'
import { Route as AuthenticatedDevisEditDevisIdRouteImport } from './routes/_authenticated/devis-edit.$devisId'
import { Route as AuthenticatedClientsNewRouteImport } from './routes/_authenticated/clients.new'
import { Route as AuthenticatedClientsClientIdEditRouteImport } from './routes/_authenticated/clients.$clientId.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDevisIndexRoute = AuthenticatedDevisIndexRouteImport.update({
  id: '/devis/',
  path: '/devis/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDevisNewRoute = AuthenticatedDevisNewRouteImport.update({
  id: '/devis/new',
  path: '/devis/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDevisDevisIdRoute =
  AuthenticatedDevisDevisIdRouteImport.update({
    id: '/devis/$devisId',
    path: '/devis/$devisId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDevisEditDevisIdRoute =
  AuthenticatedDevisEditDevisIdRouteImport.update({
    id: '/devis-edit/$devisId',
    path: '/devis-edit/$devisId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientsNewRoute = AuthenticatedClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientsClientIdEditRoute =
  AuthenticatedClientsClientIdEditRouteImport.update({
    id: '/clients/$clientId/edit',
    path: '/clients/$clientId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/clients/new': typeof AuthenticatedClientsNewRoute
  '/devis-edit/$devisId': typeof AuthenticatedDevisEditDevisIdRoute
  '/devis/$devisId': typeof AuthenticatedDevisDevisIdRoute
  '/devis/new': typeof AuthenticatedDevisNewRoute
  '/clients/': typeof AuthenticatedClientsIndexRoute
  '/devis/': typeof AuthenticatedDevisIndexRoute
  '/clients/$clientId/edit': typeof AuthenticatedClientsClientIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/clients/new': typeof AuthenticatedClientsNewRoute
  '/devis-edit/$devisId': typeof AuthenticatedDevisEditDevisIdRoute
  '/devis/$devisId': typeof AuthenticatedDevisDevisIdRoute
  '/devis/new': typeof AuthenticatedDevisNewRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/devis': typeof AuthenticatedDevisIndexRoute
  '/clients/$clientId/edit': typeof AuthenticatedClientsClientIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/clients/new': typeof AuthenticatedClientsNewRoute
  '/_authenticated/devis-edit/$devisId': typeof AuthenticatedDevisEditDevisIdRoute
  '/_authenticated/devis/$devisId': typeof AuthenticatedDevisDevisIdRoute
  '/_authenticated/devis/new': typeof AuthenticatedDevisNewRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
  '/_authenticated/devis/': typeof AuthenticatedDevisIndexRoute
  '/_authenticated/clients/$clientId/edit': typeof AuthenticatedClientsClientIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/clients/new'
    | '/devis-edit/$devisId'
    | '/devis/$devisId'
    | '/devis/new'
    | '/clients/'
    | '/devis/'
    | '/clients/$clientId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/clients/new'
    | '/devis-edit/$devisId'
    | '/devis/$devisId'
    | '/devis/new'
    | '/clients'
    | '/devis'
    | '/clients/$clientId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/clients/new'
    | '/_authenticated/devis-edit/$devisId'
    | '/_authenticated/devis/$devisId'
    | '/_authenticated/devis/new'
    | '/_authenticated/clients/'
    | '/_authenticated/devis/'
    | '/_authenticated/clients/$clientId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/devis/': {
      id: '/_authenticated/devis/'
      path: '/devis'
      fullPath: '/devis/'
      preLoaderRoute: typeof AuthenticatedDevisIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/devis/new': {
      id: '/_authenticated/devis/new'
      path: '/devis/new'
      fullPath: '/devis/new'
      preLoaderRoute: typeof AuthenticatedDevisNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/devis/$devisId': {
      id: '/_authenticated/devis/$devisId'
      path: '/devis/$devisId'
      fullPath: '/devis/$devisId'
      preLoaderRoute: typeof AuthenticatedDevisDevisIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/devis-edit/$devisId': {
      id: '/_authenticated/devis-edit/$devisId'
      path: '/devis-edit/$devisId'
      fullPath: '/devis-edit/$devisId'
      preLoaderRoute: typeof AuthenticatedDevisEditDevisIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients/new': {
      id: '/_authenticated/clients/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof AuthenticatedClientsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients/$clientId/edit': {
      id: '/_authenticated/clients/$clientId/edit'
      path: '/clients/$clientId/edit'
      fullPath: '/clients/$clientId/edit'
      preLoaderRoute: typeof AuthenticatedClientsClientIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedClientsNewRoute: typeof AuthenticatedClientsNewRoute
  AuthenticatedDevisEditDevisIdRoute: typeof AuthenticatedDevisEditDevisIdRoute
  AuthenticatedDevisDevisIdRoute: typeof AuthenticatedDevisDevisIdRoute
  AuthenticatedDevisNewRoute: typeof AuthenticatedDevisNewRoute
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
  AuthenticatedDevisIndexRoute: typeof AuthenticatedDevisIndexRoute
  AuthenticatedClientsClientIdEditRoute: typeof AuthenticatedClientsClientIdEditRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedClientsNewRoute: AuthenticatedClientsNewRoute,
  AuthenticatedDevisEditDevisIdRoute: AuthenticatedDevisEditDevisIdRoute,
  AuthenticatedDevisDevisIdRoute: AuthenticatedDevisDevisIdRoute,
  AuthenticatedDevisNewRoute: AuthenticatedDevisNewRoute,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
  AuthenticatedDevisIndexRoute: AuthenticatedDevisIndexRoute,
  AuthenticatedClientsClientIdEditRoute: AuthenticatedClientsClientIdEditRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
